### ISSUE TITLE
[QUESTION] Setup automated release pipeline 

### ISSUE THREAD

**Issue by Ambro17** [Kludex/python-multipart#56]
After #54 we now have a way to build wheels and source distributions as we adhere to latest packaging PEPs so it would be nice to setup an automated way to create new releases. I have a few questions before sending a PR

My initial approach would be to do it via github actions, running the test suite with each supported python version BUT
should a new release be created on every merge to master? Or on every manual git tagging?

Would you prefer to avoid github actions for any reason? In my head, the github action yaml should invoke commands that also exist locally. Something like
```
- inv build
- inv test
- inv bump minor
- inv publish
```
so it can be called locally, or via a github action or any other CI solution

I can also create a first working idea and iterate over that but i thought it might be more efficient to avoid certain ideas if you have preferences 

Related #50 #41 #37 #40

**Comment by Kludex** [comment]
> My initial approach would be to do it via github actions, running the test suite with each supported python version BUT
should a new release be created on every merge to master? Or on every manual git tagging?

It should be on every manual git tagging. We should aim to do things similarly (or the same) as the [encode projects](https://github.com/encode/uvicorn/tree/master/.github/workflows) - mainly because it's easier for us if it's like this.

> Would you prefer to avoid github actions for any reason?

No, no. We want it. :pray:

**Comment by Kludex** [comment]
I think the flow needs to be approved by @andrew-d, and that's why it didn't work out :sweat:
